apiVersion: v1
kind: PersistentVolume
metadata:
  name: c-test-pv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/wsl/test_mount"
    type: Directory