apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: c-test-pvc
  namespace: argo
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi