# https://argo-workflows.readthedocs.io/en/latest/fields/#workflowspec
# https://argo-workflows.readthedocs.io/en/latest/workflow-concepts/

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: sleap-roots-pipeline-
  namespace: argo
spec:
  entrypoint: pipeline
  arguments:
    parameters:
      - name: models-input-dir
        value: "/workspace/input"
      - name: models-output-dir
        value: "/workspace/output"

  volumes:
    - name: pipeline-storage
      persistentVolumeClaim:
        claimName: local-artifacts-pvc

  templates:
  - name: pipeline
    dag:
      tasks:
      - name: models-downloader
        template: models-downloader

  - name: models-downloader
    container:
      image: registry.gitlab.com/salk-tm/models-downloader:latest
      command: ["python", "/workspace/src/main.py"]
      args:
        - "{{workflow.parameters.models-input-dir}}"
        - "{{workflow.parameters.models-output-dir}}"
      securityContext:
        privileged: true
        runAsUser: 0
      volumeMounts:
        - name: pipeline-storage
          mountPath: /workspace

