apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: sleap-roots-trait-extractor-template
  labels:
    project: talmo-lab
  annotations:
    preemptible: "true"
spec:
  templates:
    - name: sleap-roots-trait-extractor
      retryStrategy:
        limit: 2
        retryPolicy: Always
      container:
        image: registry.gitlab.com/salk-tm/sleap-roots-traits:latest
        imagePullPolicy: Always
        args:
          - "python"
          - "/workspace/src/main.py"
          - "/workspace/input"
          - "/workspace/output"
        volumeMounts:
          - name: predictions-output-dir
            mountPath: /workspace/input
          - name: traits-output-dir
            mountPath: /workspace/output
        securityContext:
          privileged: true
          runAsUser: 0
